### ISSUE TITLE
Authentication quit working

### ISSUE THREAD

**Issue by ryancornia** [ianjwhite99/sync-connect-sdk#58]
I had a script that worked regularly until about 2 weeks ago, and is now failing when trying to get the access token:

  File "/.local/lib/python3.8/site-packages/connectedcar/connectedcar.py", line 63, in get_user_access_token
    response = requester.call(
  File "/.local/lib/python3.8/site-packages/connectedcar/requester.py", line 47, in call
    raise e
  File "/.local/lib/python3.8/site-packages/connectedcar/requester.py", line 29, in call
    raise E.ValidationException(response)
connectedcar.exceptions.ValidationException: CSIAQ0172E The grant type [password] is not supported. Supported grant types are [authorization_code, refresh_token].

**To Reproduce**
`    odo['odometer'] =  odo.pop('data');

"/data/ryan@roadtripryan.com/personal/ranger.py" 32L, 1039C                                                                                                      1,1           Top
#!/usr/bin/python3

import connectedcar
import json

client = connectedcar.AuthClient(
    '9fb503e0-715b-47e8-adfd-ad4b7770f73b',
    None,
    None)  # Create client connection
access = client.get_user_access_token(
    '<my username>', '<my password>')  # Fetch client access token

user = connectedcar.User(access['access_token'])  # New User Object
vehicles = user.vehicles()  # Fetch list of user vehicles
`

**Expected behavior**
I expected to get an access token and list of vehicles. 

**Desktop (please complete the following information):**
 - 20.04.4 LTS (Focal Fossa)
 - Python 3.8.10
 - python3 -m pip install --upgrade connectedcar
Requirement already up-to-date: connectedcar in ./.local/lib/python3.8/site-packages (1.3.5)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from connectedcar) (2.22.0)

**Comment by ianjwhite99** [comment]
Hi @ryancornia, I will look into this for you!

**Comment by ianjwhite99** [comment]
Looks like Ford has disabled the OAuth password grant based on the error response `CSIAQ0172E The grant type [password] is not supported. Supported grant types are [authorization_code, refresh_token]`.

**Comment by ianjwhite99** [comment]
Authentication has been fixed for the [Node SDK](https://github.com/ianjwhite99/connected-car-node-sdk). Python fix will come later today ;)

**Comment by ianjwhite99** [comment]
This is fixed with [v1.3.6](https://github.com/ianjwhite99/connected-car-python-sdk/releases/tag/1.3.6)
