### ISSUE TITLE
502 Gateway error

### ISSUE THREAD

**Issue by Krisp1k** [ianjwhite99/sync-connect-sdk#59]
Python script throws a 502 Gateway error upon reaching any line that's using the access key (pic 1). I tried using every possible combination of the refreshToken and access variable with refresh_token or access_token in dict, but nothing worked. I even tried some client-side fixes like flushing DNS, but nothing. Here's the code (pic 2)

In this example the code is working fine until reaching the "vehicles" variable. 

In theory it could be that the Ford changed their api endpoint, but that's unsure. Yesterday the code was working fine but today.

_Note : even the file in examples folder in this repo doesn't work, same error_

![pic 1 -error](https://user-images.githubusercontent.com/75334703/179930968-cb262f9d-161f-45d7-a0e0-318a45f19fc8.JPG)
![pic 2 - code](https://user-images.githubusercontent.com/75334703/179930973-7c94fbbd-07df-40ce-9658-aa1bb9f57f9b.JPG)

**Comment by lostbrother** [comment]
I am also getting the same error. I had thought I was doing something wrong, but I also noticed https://github.com/clarkd/fordpass-python was giving me errors.

**Comment by avesely20** [comment]
I have the same issue, I think it's because there is country=USA and region=US in the URL

**Comment by ianjwhite99** [comment]
Hi guys, sorry I've been on vacation and am just now getting around to this. It looks like Ford changed their API endpoint. I'll work on trying to get a fix for this pushed later today!
