### ISSUE TITLE
Ford Account Lockout

### ISSUE THREAD

**Issue by ianjwhite99** [ianjwhite99/sync-connect-sdk#69]
Hi all,

It seems Ford has started cracking down on third party services taking advantage of their apis. 

Recently I was locked out of my account and after speaking to Ford support they told me it was because of an unauthorized third party service using my credentials, which would be connected-car SDK's.

I am curious if anyone else has experienced this issue?

**Comment by larsonsamj** [comment]
I had the same issue. Called and after a month or two they finally found someone who could help. Was told it was against their TOS to use 3rd party integrations and they’ll unlock me one time but if it happens again I’ll be locked out for good. So I quit using it unfortunately.

**Comment by ianjwhite99** [comment]
> I had the same issue. Called and after a month or two they finally found someone who could help. Was told it was against their TOS to use 3rd party integrations and they’ll unlock me one time but if it happens again I’ll be locked out for good. So I quit using it unfortunately.

Interesting, I'm not sure what they're doing to detect unauthrozied use of their api's. I would assume it's the `User-Agent:` in the request headers but I'm not sure. I will have to look into it and see if I can find a work around.

**Comment by kenbolton** [comment]
One session using this otherwise excellent software led to an account lockout. I'm now "dead in the water", as it were.

I don't see a commit associated with closing this issue.

**Comment by ianjwhite99** [comment]
@kenbolton The account lockout issue was resolved with release [v1.3.10](https://github.com/ianjwhite99/connected-car-python-sdk/releases/tag/1.3.10): pull request #70. The User-Agent was the culprit as the SDK was sending across a depreciated FordPass UA version. 

Please reference discussion #71 about account lock out or visit issue [#37](https://github.com/ianjwhite99/connected-car-node-sdk/issues/37) in the [Connected Car Node SDK](https://github.com/ianjwhite99/connected-car-node-sdk). Making an assumption based on other account lock issues, I would attribute your account lock to making too many API requests in a short period of time. If you wish to unlock your account you will need to contact FordPass support.

**Comment by kenbolton** [comment]
Is https://connectedcar-sdk.com/ running v1.3.10?

I've been in touch with Ford and they've assured me they will work on it promptly on Monday.

**Comment by ianjwhite99** [comment]
https://connectedcar-sdk.com runs v1.2.12 of the Connected Car Node SDK, which is the latest version. You can view the source code for that site in the [Connected Car Node API](https://github.com/ianjwhite99/connected-car-node-api) repo.
